"""Tests for scripts/spreading_builder.py.

openpyxl only stores formula strings -- it does not calculate them -- so the
formula-correctness tests below include a small recursive evaluator that
resolves cell references and re-implements the handful of Excel functions
the workbook actually uses (SUM, IFERROR). It exists only to let tests
assert on computed values without depending on Excel or LibreOffice being
installed in CI.
"""
import re

import pytest
import openpyxl

from spreading_builder import export_to_xlsx, SECTIONS, COLLATERAL_HEADERS

CELL_REF_RE = re.compile(r"([A-Z]+)(\d+)")


@pytest.fixture
def workbook(tmp_path):
    out_path = tmp_path / "test_deal.xlsx"
    export_to_xlsx("Test Co", str(out_path))
    return openpyxl.load_workbook(out_path)


def _evaluate(ws, col, row, memo):
    key = (col, row)
    if key in memo:
        return memo[key]
    raw = ws[f"{col}{row}"].value
    if raw is None:
        result = 0
    elif isinstance(raw, (int, float)):
        result = raw
    elif isinstance(raw, str) and raw.startswith("="):
        result = _eval_expr(ws, raw[1:], memo)
    else:
        raise AssertionError(f"Unexpected non-numeric, non-formula value at {col}{row}: {raw!r}")
    memo[key] = result
    return result


def _eval_expr(ws, expr, memo):
    m = re.fullmatch(r"SUM\(([A-Z]+)(\d+):([A-Z]+)(\d+)\)", expr)
    if m:
        col1, r1, col2, r2 = m.group(1), int(m.group(2)), m.group(3), int(m.group(4))
        assert col1 == col2, f"Unsupported multi-column SUM range: {expr}"
        return sum(_evaluate(ws, col1, r, memo) for r in range(r1, r2 + 1))

    m = re.fullmatch(r"IFERROR\((.+),(-?\d+(?:\.\d+)?)\)", expr)
    if m:
        inner, fallback = m.group(1), float(m.group(2))
        try:
            return _eval_arith(ws, inner, memo)
        except ZeroDivisionError:
            return fallback

    return _eval_arith(ws, expr, memo)


def _eval_arith(ws, expr, memo):
    def repl(match):
        col, row = match.group(1), int(match.group(2))
        return repr(_evaluate(ws, col, row, memo))

    substituted = CELL_REF_RE.sub(repl, expr)
    # Formulas are generated by spreading_builder.py itself (not user input),
    # and every cell reference has already been replaced with a numeric
    # literal, so eval() here only ever runs arithmetic on numbers.
    return eval(substituted, {"__builtins__": {}}, {})


# ---------------------------------------------------------------------------
# Structure
# ---------------------------------------------------------------------------

def test_creates_expected_sheets(workbook):
    assert workbook.sheetnames == ["Financial Spreading", "Collateral & Exposure"]


def test_financial_spreading_header_row(workbook):
    ws = workbook["Financial Spreading"]
    assert [c.value for c in ws[1]] == ["Metric", "FY-2", "FY-1", "FY-Current"]


def test_financial_spreading_row_labels_match_section_definitions(workbook):
    ws = workbook["Financial Spreading"]
    expected_labels = ["Metric"]
    for section_title, rows in SECTIONS:
        expected_labels.append(section_title)
        expected_labels.extend(label for label, _ in rows)

    actual_labels = [ws.cell(row=r, column=1).value for r in range(1, ws.max_row + 1)]
    assert actual_labels == expected_labels


def test_collateral_sheet_headers(workbook):
    ws = workbook["Collateral & Exposure"]
    assert [c.value for c in ws[1]] == COLLATERAL_HEADERS


def test_collateral_sheet_has_a_total_row(workbook):
    ws = workbook["Collateral & Exposure"]
    assert ws.cell(row=3, column=1).value == "Total"


# ---------------------------------------------------------------------------
# Formula correctness
#
# Every formula in the "Financial Spreading" sheet references other rows by
# absolute row number (see the comment above the row definitions in
# spreading_builder.py). These tests fill in every raw-input row with a
# hand-picked value, then check each derived cell against a value computed
# by hand from those same inputs -- so a row insertion/deletion that silently
# shifts a formula's cell references (as happened once during development)
# fails loudly instead of quietly pointing at the wrong row.
# ---------------------------------------------------------------------------

RAW_INPUTS = {
    "Revenue": 1000,
    "Cost of Goods Sold": 400,
    "Admin Expenses": 100,
    "Depreciation": 50,
    "Amortisation": 20,
    "Other Income": 10,
    "Interest Paid": 30,
    "Interest Received": 5,
    "Exceptional Costs / (Income)": 0,
    "Tax": 40,
    "Tangible Fixed Assets": 500,
    "Intangible Fixed Assets": 50,
    "Investments": 20,
    "Cash": 60,
    "Accounts Receivable": 80,
    "Stock": 90,
    "Other Current Assets": 10,
    "Accounts Payable": 70,
    "Current Portion - Debt": 15,
    "Overdraft / Revolving Debt": 5,
    "Other Current Liabilities": 10,
    "Long Term Debt": 300,
    "Loan Notes / Preference Shares": 25,
    "Other Long Term Liabilities": 10,
    "Provisions": 5,
    "Share Capital": 100,
    "Retained Profit": 200,
    "Trade Debtor Days": 40,
    "Trade Creditor Days": 35,
    "Stock Days": 60,
}

# Hand-calculated from RAW_INPUTS above.
EXPECTED = {
    "Gross Profit": 600,
    "Gross Profit Margin %": pytest.approx(0.6),
    "Operating Profit": 440,
    "Operating Margin %": pytest.approx(0.44),
    "EBITDA": 510,
    "Profit Before Tax": 415,
    "Net Profit": 375,
    "EBIT/Interest": pytest.approx(440 / 30),
    "EBITDA/Interest": pytest.approx(17.0),
    "Total Fixed Assets": 570,
    "Total Current Assets": 240,
    "Total Assets": 810,
    "Total Current Liabilities": 100,
    "Total Long Term Liabilities": 340,
    "Total Liabilities": 440,
    "Total Equity": 300,
    "Tangible Net Worth (TNW)": 250,
    "TNW + Loan Notes / Preference Shares": 275,
    "Gearing % (Interest-Bearing Debt / Equity)": pytest.approx(345 / 300),
    "Current Ratio": pytest.approx(2.4),
    "Working Capital Cycle (days)": 65,
}


def test_formula_results_match_hand_calculated_values(workbook):
    ws = workbook["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    for label, value in RAW_INPUTS.items():
        ws.cell(row=label_to_row[label], column=2, value=value)

    memo = {}
    for label, expected in EXPECTED.items():
        actual = _evaluate(ws, "B", label_to_row[label], memo)
        assert actual == expected, f"{label} (row {label_to_row[label]}): expected {expected}, got {actual}"


def test_iferror_falls_back_to_zero_on_division_by_zero(workbook):
    """Every raw input left blank (0) should not raise ZeroDivisionError."""
    ws = workbook["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    memo = {}
    ratio_labels = [
        "Gross Profit Margin %", "Operating Margin %", "EBIT/Interest",
        "EBITDA/Interest", "Gearing % (Interest-Bearing Debt / Equity)", "Current Ratio",
    ]
    for label in ratio_labels:
        assert _evaluate(ws, "B", label_to_row[label], memo) == 0
