"""Tests for scripts/spreading_builder.py.

openpyxl only stores formula strings -- it does not calculate them -- so the
formula-correctness tests below include a small recursive evaluator that
resolves cell references and re-implements the handful of Excel functions
the workbook actually uses (SUM, IFERROR). It exists only to let tests
assert on computed values without depending on Excel or LibreOffice being
installed in CI.
"""
import re

import pytest
import openpyxl

from spreading_builder import (
    COLLATERAL_HEADERS,
    SECTIONS,
    apply_stress_shocks,
    evaluate_downside_case,
    evaluate_financial_model,
    export_to_xlsx,
    validate_row_formulas,
)

CELL_REF_RE = re.compile(r"([A-Z]+)(\d+)")


@pytest.fixture
def workbook(tmp_path):
    out_path = tmp_path / "test_deal.xlsx"
    export_to_xlsx("Test Co", str(out_path))
    return openpyxl.load_workbook(out_path)


def _evaluate(ws, col, row, memo):
    key = (col, row)
    if key in memo:
        return memo[key]
    raw = ws[f"{col}{row}"].value
    if raw is None:
        result = 0
    elif isinstance(raw, (int, float)):
        result = raw
    elif isinstance(raw, str) and raw.startswith("="):
        result = _eval_expr(ws, raw[1:], memo)
    else:
        raise AssertionError(f"Unexpected non-numeric, non-formula value at {col}{row}: {raw!r}")
    memo[key] = result
    return result


def _eval_expr(ws, expr, memo):
    m = re.fullmatch(r"SUM\(([A-Z]+)(\d+):([A-Z]+)(\d+)\)", expr)
    if m:
        col1, r1, col2, r2 = m.group(1), int(m.group(2)), m.group(3), int(m.group(4))
        assert col1 == col2, f"Unsupported multi-column SUM range: {expr}"
        return sum(_evaluate(ws, col1, r, memo) for r in range(r1, r2 + 1))

    m = re.fullmatch(r"IFERROR\((.+),(-?\d+(?:\.\d+)?)\)", expr)
    if m:
        inner, fallback = m.group(1), float(m.group(2))
        try:
            return _eval_arith(ws, inner, memo)
        except ZeroDivisionError:
            return fallback

    return _eval_arith(ws, expr, memo)


def _eval_arith(ws, expr, memo):
    def repl(match):
        col, row = match.group(1), int(match.group(2))
        return repr(_evaluate(ws, col, row, memo))

    substituted = CELL_REF_RE.sub(repl, expr)
    # Formulas are generated by spreading_builder.py itself (not user input),
    # and every cell reference has already been replaced with a numeric
    # literal, so eval() here only ever runs arithmetic on numbers.
    return eval(substituted, {"__builtins__": {}}, {})


# ---------------------------------------------------------------------------
# Structure
# ---------------------------------------------------------------------------

def test_creates_expected_sheets(workbook):
    assert workbook.sheetnames == ["Financial Spreading", "Collateral & Exposure"]


def test_financial_spreading_header_row(workbook):
    ws = workbook["Financial Spreading"]
    assert [c.value for c in ws[1]] == ["Metric", "FY-2", "FY-1", "FY-Current"]


def test_financial_spreading_row_labels_match_section_definitions(workbook):
    ws = workbook["Financial Spreading"]
    expected_labels = ["Metric"]
    for section_title, rows in SECTIONS:
        expected_labels.append(section_title)
        expected_labels.extend(label for label, _ in rows)

    actual_labels = [ws.cell(row=r, column=1).value for r in range(1, ws.max_row + 1)]
    assert actual_labels == expected_labels


def test_dscr_is_in_key_ratios_and_gross_leverage_is_in_key_credit_metrics():
    """DSCR needs only P&L rows (available inside "Key Ratios", which comes
    right after "Profit & Loss"); Gross Leverage needs Balance Sheet debt
    rows, so it must live in "Key Credit Metrics" (written after "Balance
    Sheet") rather than back in "Key Ratios" -- otherwise it would be a
    forward reference and validate_row_formulas() would reject it."""
    sections_by_title = dict(SECTIONS)
    key_ratio_labels = [label for label, _ in sections_by_title["Key Ratios"]]
    key_metric_labels = [label for label, _ in sections_by_title["Key Credit Metrics"]]

    assert "DSCR" in key_ratio_labels
    assert "Gross Leverage" not in key_ratio_labels
    assert "Gross Leverage" in key_metric_labels


def test_collateral_sheet_headers(workbook):
    ws = workbook["Collateral & Exposure"]
    assert [c.value for c in ws[1]] == COLLATERAL_HEADERS
    assert "Perfection Status" in COLLATERAL_HEADERS


def test_collateral_sheet_has_a_total_row(workbook):
    ws = workbook["Collateral & Exposure"]
    assert ws.cell(row=3, column=1).value == "Total"


# ---------------------------------------------------------------------------
# Formula correctness
#
# Every formula in the "Financial Spreading" sheet references other rows by
# label (see FIELD_LABELS / the {Label} syntax in spreading_builder.py),
# resolved to an absolute cell reference at write time. These tests fill in
# every raw-input row with a hand-picked value, then check each derived cell
# against a value computed by hand from those same inputs -- so a row
# insertion/deletion/reorder that silently breaks a formula's dependency
# fails loudly instead of quietly pointing at the wrong row.
# ---------------------------------------------------------------------------

RAW_INPUTS = {
    "Revenue": 1000,
    "Cost of Goods Sold": 400,
    "Admin Expenses": 100,
    "Depreciation": 50,
    "Amortisation": 20,
    "Other Income": 10,
    "Interest Paid": 30,
    "Interest Received": 5,
    "Scheduled Principal Repayment": 70,
    "Exceptional Costs / (Income)": 0,
    "Tax": 40,
    "Tangible Fixed Assets": 500,
    "Intangible Fixed Assets": 50,
    "Investments": 20,
    "Cash": 60,
    "Accounts Receivable": 80,
    "Stock": 90,
    "Other Current Assets": 10,
    "Accounts Payable": 70,
    "Current Portion - Debt": 15,
    "Overdraft / Revolving Debt": 5,
    "Other Current Liabilities": 10,
    "Long Term Debt": 300,
    "Loan Notes / Preference Shares": 25,
    "Other Long Term Liabilities": 10,
    "Provisions": 5,
    "Share Capital": 100,
    "Retained Profit": 200,
    "Trade Debtor Days": 40,
    "Trade Creditor Days": 35,
    "Stock Days": 60,
}

# Hand-calculated from RAW_INPUTS above.
# Total interest-bearing debt = 15 + 5 + 300 + 25 = 345.
EXPECTED = {
    "Gross Profit": 600,
    "Gross Profit Margin %": pytest.approx(0.6),
    "Operating Profit": 440,
    "Operating Margin %": pytest.approx(0.44),
    "EBITDA": 510,
    "Profit Before Tax": 415,
    "Net Profit": 375,
    "DSCR": pytest.approx(510 / (30 + 70)),
    "EBIT/Interest": pytest.approx(440 / 30),
    "EBITDA/Interest": pytest.approx(17.0),
    "Total Fixed Assets": 570,
    "Total Current Assets": 240,
    "Total Assets": 810,
    "Total Current Liabilities": 100,
    "Total Long Term Liabilities": 340,
    "Total Liabilities": 440,
    "Total Equity": 300,
    "Tangible Net Worth (TNW)": 250,
    "TNW + Loan Notes / Preference Shares": 275,
    "Gearing % (Interest-Bearing Debt / Equity)": pytest.approx(345 / 300),
    "Current Ratio": pytest.approx(2.4),
    "Gross Leverage": pytest.approx(345 / 510),
    "Working Capital Cycle (days)": 65,
}


def test_formula_results_match_hand_calculated_values(workbook):
    ws = workbook["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    for label, value in RAW_INPUTS.items():
        ws.cell(row=label_to_row[label], column=2, value=value)

    memo = {}
    for label, expected in EXPECTED.items():
        actual = _evaluate(ws, "B", label_to_row[label], memo)
        assert actual == expected, f"{label} (row {label_to_row[label]}): expected {expected}, got {actual}"


def test_scheduled_principal_only_affects_dscr(workbook):
    """The Accounting Guard: Scheduled Principal Repayment is a DSCR-only
    memo line and must never enter the Profit Before Tax / Net Profit chain."""
    ws = workbook["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    for label, value in RAW_INPUTS.items():
        ws.cell(row=label_to_row[label], column=2, value=value)

    memo_with_principal = {}
    dscr_with_principal = _evaluate(ws, "B", label_to_row["DSCR"], dict(memo_with_principal))
    pbt_with_principal = _evaluate(ws, "B", label_to_row["Profit Before Tax"], dict(memo_with_principal))
    net_profit_with_principal = _evaluate(ws, "B", label_to_row["Net Profit"], dict(memo_with_principal))

    ws.cell(row=label_to_row["Scheduled Principal Repayment"], column=2, value=0)
    memo_without_principal = {}
    dscr_without_principal = _evaluate(ws, "B", label_to_row["DSCR"], memo_without_principal)
    pbt_without_principal = _evaluate(ws, "B", label_to_row["Profit Before Tax"], memo_without_principal)
    net_profit_without_principal = _evaluate(ws, "B", label_to_row["Net Profit"], memo_without_principal)

    assert dscr_with_principal != dscr_without_principal
    assert pbt_with_principal == pbt_without_principal == 415
    assert net_profit_with_principal == net_profit_without_principal == 375


def test_iferror_falls_back_to_zero_on_division_by_zero(workbook):
    """Every raw input left blank (0) should not raise ZeroDivisionError."""
    ws = workbook["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    memo = {}
    ratio_labels = [
        "Gross Profit Margin %", "Operating Margin %", "DSCR", "EBIT/Interest",
        "EBITDA/Interest", "Gearing % (Interest-Bearing Debt / Equity)",
        "Current Ratio", "Gross Leverage",
    ]
    for label in ratio_labels:
        assert _evaluate(ws, "B", label_to_row[label], memo) == 0


# ---------------------------------------------------------------------------
# Runtime row-to-formula validation
#
# validate_row_formulas() derives each row's real position from `sections`
# itself and checks every formula's label dependencies against that -- these
# tests confirm it accepts the real (correct) SECTIONS and rejects a
# deliberately broken one.
# ---------------------------------------------------------------------------

def test_validate_row_formulas_passes_on_the_real_sections():
    validate_row_formulas(SECTIONS)  # must not raise, after the section reshuffle


def test_export_to_xlsx_validates_before_writing(tmp_path):
    """export_to_xlsx() must run the same check the unit tests do, not just CI."""
    export_to_xlsx("Test Co", str(tmp_path / "out.xlsx"))  # must not raise


def test_validate_row_formulas_rejects_a_forward_reference():
    # Row 3: "B (broken)" references "C", which is written on row 4 -- after
    # it -- so "C" doesn't exist yet when row 3 is written.
    broken_sections = [
        ("Test Section", [
            ("A", None),
            ("B (broken)", "={C}"),
            ("C", None),
        ]),
    ]
    with pytest.raises(ValueError, match="B \\(broken\\)"):
        validate_row_formulas(broken_sections)


def test_validate_row_formulas_rejects_a_self_reference():
    broken_sections = [
        ("Test Section", [
            ("A (broken)", "={A (broken)}"),  # row 3 referencing itself
        ]),
    ]
    with pytest.raises(ValueError, match="row 3"):
        validate_row_formulas(broken_sections)


def test_validate_row_formulas_rejects_an_unknown_label():
    broken_sections = [
        ("Test Section", [
            ("A (broken)", "={Nonexistent Label}"),
        ]),
    ]
    with pytest.raises(ValueError, match="unknown label"):
        validate_row_formulas(broken_sections)


# ---------------------------------------------------------------------------
# evaluate_financial_model(): the programmatic single source of truth for
# subtotals/ratios, independent of the Excel formulas (used for LLM
# grounding context and state.json's financials/ratios keys).
# ---------------------------------------------------------------------------

SAMPLE_PERIOD = {
    "revenue": 1000, "cost_of_sales": 400, "admin_expenses": 100,
    "depreciation": 50, "amortisation": 20, "other_income": 10,
    "interest_paid": 30, "interest_received": 5, "scheduled_principal": 70,
    "exceptional_costs": 0, "tax_paid": 40,
    "cash": 60, "trade_debtors": 80, "stock": 90, "other_current_assets": 10,
    "tangible_assets": 500, "intangible_assets": 50, "other_fixed_assets": 20,
    "trade_creditors": 70, "other_current_liabilities": 10,
    "overdraft": 5, "current_debt": 15, "long_term_debt": 300, "loan_notes": 25,
    "share_capital": 100, "retained_profit": 200,
}


def test_evaluate_financial_model_matches_hand_calculated_workbook_values():
    result = evaluate_financial_model({"FY-Current": SAMPLE_PERIOD})

    financials = result["financials"]["FY-Current"]
    ratios = result["ratios"]["FY-Current"]

    assert financials["ebitda"] == 510
    assert financials["profit_before_tax"] == 415
    assert financials["net_profit"] == 375
    assert financials["tangible_net_worth"] == 250
    assert financials["total_debt"] == 345

    assert ratios["dscr"] == pytest.approx(510 / 100)
    assert ratios["gross_leverage"] == pytest.approx(345 / 510)
    assert ratios["current_ratio"] == pytest.approx(2.4)
    assert ratios["ebit_interest_cover"] == pytest.approx(440 / 30)
    assert ratios["ebitda_interest_cover"] == pytest.approx(17.0)
    # Aliases matching the Excel row labels must agree with their snake_case originals.
    assert ratios["EBIT/Interest"] == ratios["ebit_interest_cover"]
    assert ratios["EBITDA/Interest"] == ratios["ebitda_interest_cover"]


def test_evaluate_financial_model_handles_multiple_periods_independently():
    result = evaluate_financial_model({
        "FY-2": {**SAMPLE_PERIOD, "revenue": 500},
        "FY-Current": SAMPLE_PERIOD,
    })

    assert result["financials"]["FY-2"]["gross_profit"] == 100
    assert result["financials"]["FY-Current"]["gross_profit"] == 600


def test_evaluate_financial_model_handles_empty_input():
    assert evaluate_financial_model({}) == {"financials": {}, "ratios": {}}
    assert evaluate_financial_model(None) == {"financials": {}, "ratios": {}}


def test_evaluate_financial_model_defaults_missing_fields_to_zero():
    result = evaluate_financial_model({"FY-Current": {"revenue": 100}})
    financials = result["financials"]["FY-Current"]
    ratios = result["ratios"]["FY-Current"]

    assert financials["gross_profit"] == 100
    # No interest/principal at all -> DSCR is undefined (no debt service
    # obligation to cover), not a coverage ratio of literal zero -- see
    # test_zero_denominator_ratios_are_undefined_not_zero below for why.
    assert ratios["dscr"] is None


def test_zero_denominator_ratios_are_undefined_not_zero():
    """A debt-free company (zero interest, zero principal) has undefined --
    not zero -- coverage ratios: reporting 0 would misrepresent "no debt
    service obligation" as "failing to cover it at all", which would wrongly
    fail a real DSCR/interest-cover covenant for a company with no debt.
    Likewise zero current liabilities (undefined current ratio) and zero
    equity (undefined gearing) must not silently read as "0", which would
    hide rather than surface those situations.
    """
    result = evaluate_financial_model({
        "FY-Current": {
            "revenue": 1000, "cost_of_sales": 400,
            "interest_paid": 0, "scheduled_principal": 0,
            # current_liabilities = trade_creditors + current_debt + overdraft
            # + other_current_liabilities, all defaulted to 0 -> undefined current_ratio.
            # total_equity = share_capital + retained_profit, both defaulted
            # to 0 -> undefined gearing.
        },
    })
    ratios = result["ratios"]["FY-Current"]

    assert ratios["dscr"] is None
    assert ratios["ebit_interest_cover"] is None
    assert ratios["ebitda_interest_cover"] is None
    assert ratios["EBIT/Interest"] is None
    assert ratios["EBITDA/Interest"] is None
    assert ratios["current_ratio"] is None
    assert ratios["gearing"] is None
    # total_debt is legitimately 0 here (no debt fields given) and EBITDA is
    # a genuine nonzero 600 -- 0/600 is a well-defined, correct 0.0 leverage,
    # not an undefined-denominator case like the others above.
    assert ratios["gross_leverage"] == 0.0


def test_nonzero_denominator_ratios_still_compute_normally_including_negative_equity():
    """Confirms the None-for-zero-denominator change doesn't affect any
    ratio whose denominator is genuinely nonzero -- including a legitimate
    (if alarming) negative-equity gearing ratio, which must still compute
    rather than being coerced to None or 0."""
    result = evaluate_financial_model({
        "FY-Current": {
            "revenue": 1000, "cost_of_sales": 400,
            "share_capital": 100, "retained_profit": -500,  # total_equity = -400
            "current_debt": 200,
        },
    })
    ratios = result["ratios"]["FY-Current"]
    assert ratios["gearing"] == pytest.approx(200 / -400)


# ---------------------------------------------------------------------------
# Forward periods (FY+1-FY+3): evaluate_financial_model() needs zero code
# changes to handle these -- it already loops generically over whatever
# period keys it's given. These tests confirm that directly rather than
# taking it on faith.
# ---------------------------------------------------------------------------

def test_evaluate_financial_model_handles_forward_periods_with_no_special_casing():
    result = evaluate_financial_model({
        "FY-Current": SAMPLE_PERIOD,
        "FY+1": SAMPLE_PERIOD,
        "FY+2": SAMPLE_PERIOD,
        "FY+3": SAMPLE_PERIOD,
    })

    for period in ("FY-Current", "FY+1", "FY+2", "FY+3"):
        assert result["financials"][period]["ebitda"] == 510
        assert result["ratios"][period]["dscr"] == pytest.approx(510 / 100)


def test_evaluate_financial_model_forward_periods_are_grounded_input_not_derived():
    """A forward year with figures entirely different from the historical
    period must produce entirely independent results -- confirming forward
    years are treated as their own directly-supplied input, never derived
    or extrapolated from the historical period alongside them."""
    result = evaluate_financial_model({
        "FY-Current": SAMPLE_PERIOD,
        "FY+1": {**SAMPLE_PERIOD, "revenue": 2000},  # management's own forecast, e.g.
    })
    assert result["financials"]["FY-Current"]["gross_profit"] == 600
    assert result["financials"]["FY+1"]["gross_profit"] == 1600  # 2000 - 400, independent


# ---------------------------------------------------------------------------
# Stress testing: apply_stress_shocks() / evaluate_downside_case(). No LLM
# math, no invented figures -- these only ever transform an already-supplied
# forward-year base case via explicit, deterministic shocks, then re-run the
# exact same evaluate_financial_model() row chains used for the base case.
# ---------------------------------------------------------------------------

STRESS_ASSUMPTIONS = {
    "revenue_haircut_pct": 10,
    "interest_rate_bump_bps": 200,
    "opex_increase_pct": 5,
}


def test_apply_stress_shocks_revenue_haircut():
    shocked = apply_stress_shocks({"revenue": 1000}, {"revenue_haircut_pct": 10})
    assert shocked["revenue"] == pytest.approx(900)  # 1000 * (1 - 10/100)


def test_apply_stress_shocks_opex_increase_affects_only_admin_expenses():
    shocked = apply_stress_shocks(
        {"admin_expenses": 100, "cost_of_sales": 400}, {"opex_increase_pct": 5},
    )
    assert shocked["admin_expenses"] == pytest.approx(105)  # 100 * (1 + 5/100)
    assert shocked["cost_of_sales"] == 400  # untouched -- opex shock never touches COGS


def test_apply_stress_shocks_interest_rate_bump_uses_total_interest_bearing_debt():
    base = {
        "interest_paid": 30,
        "current_debt": 15, "overdraft": 5, "long_term_debt": 300, "loan_notes": 25,
    }
    shocked = apply_stress_shocks(base, {"interest_rate_bump_bps": 200})
    # total_interest_bearing_debt = 15+5+300+25 = 345; bump = 345 * 200/10000 = 6.9
    assert shocked["interest_paid"] == pytest.approx(30 + 6.9)


def test_apply_stress_shocks_leaves_other_fields_unchanged():
    shocked = apply_stress_shocks(SAMPLE_PERIOD, STRESS_ASSUMPTIONS)
    assert shocked["tax_paid"] == SAMPLE_PERIOD["tax_paid"]
    assert shocked["cash"] == SAMPLE_PERIOD["cash"]
    assert shocked["share_capital"] == SAMPLE_PERIOD["share_capital"]


def test_apply_stress_shocks_does_not_mutate_the_base_case_dict():
    original = dict(SAMPLE_PERIOD)
    apply_stress_shocks(SAMPLE_PERIOD, STRESS_ASSUMPTIONS)
    assert SAMPLE_PERIOD == original


def test_apply_stress_shocks_with_no_assumptions_is_a_no_op_for_the_shocked_fields():
    shocked = apply_stress_shocks(SAMPLE_PERIOD, {})
    assert shocked["revenue"] == SAMPLE_PERIOD["revenue"]
    assert shocked["admin_expenses"] == SAMPLE_PERIOD["admin_expenses"]
    assert shocked["interest_paid"] == SAMPLE_PERIOD["interest_paid"]


def test_evaluate_downside_case_produces_exact_expected_degraded_ebitda_and_dscr():
    """End-to-end: SAMPLE_PERIOD as FY+1's base case, stressed by
    STRESS_ASSUMPTIONS, re-run through the exact same row-chain evaluator
    as the base case -- hand-calculated expected EBITDA/DSCR."""
    result = evaluate_downside_case({"FY+1": SAMPLE_PERIOD}, STRESS_ASSUMPTIONS)

    shocked_revenue = 1000 * 0.9  # 900
    shocked_admin_expenses = 100 * 1.05  # 105
    shocked_interest_paid = 30 + (345 * 200 / 10000)  # 30 + 6.9 = 36.9

    expected_gross_profit = shocked_revenue - 400  # cost_of_sales unchanged = 400
    expected_operating_profit = expected_gross_profit - shocked_admin_expenses - 50 - 20 + 10
    expected_ebitda = expected_operating_profit + 50 + 20
    expected_dscr = expected_ebitda / (shocked_interest_paid + 70)  # scheduled_principal unchanged

    financials = result["financials"]["FY+1"]
    ratios = result["ratios"]["FY+1"]
    assert financials["ebitda"] == pytest.approx(expected_ebitda)
    assert ratios["dscr"] == pytest.approx(expected_dscr)


def test_evaluate_downside_case_never_shocks_historical_periods():
    result = evaluate_downside_case(
        {"FY-2": SAMPLE_PERIOD, "FY-1": SAMPLE_PERIOD, "FY-Current": SAMPLE_PERIOD, "FY+1": SAMPLE_PERIOD},
        STRESS_ASSUMPTIONS,
    )
    assert set(result["financials"].keys()) == {"FY+1"}
    assert "FY-2" not in result["ratios"]
    assert "FY-Current" not in result["ratios"]


def test_evaluate_downside_case_only_includes_forward_periods_actually_present():
    result = evaluate_downside_case({"FY+1": SAMPLE_PERIOD}, STRESS_ASSUMPTIONS)
    assert set(result["financials"].keys()) == {"FY+1"}
    assert "FY+2" not in result["financials"]
    assert "FY+3" not in result["financials"]


def test_evaluate_downside_case_with_no_forward_periods_returns_empty():
    result = evaluate_downside_case({"FY-Current": SAMPLE_PERIOD}, STRESS_ASSUMPTIONS)
    assert result == {"financials": {}, "ratios": {}}


def test_evaluate_downside_case_handles_multiple_forward_years_independently():
    result = evaluate_downside_case(
        {"FY+1": SAMPLE_PERIOD, "FY+2": {**SAMPLE_PERIOD, "revenue": 2000}},
        STRESS_ASSUMPTIONS,
    )
    assert result["financials"]["FY+1"]["ebitda"] != result["financials"]["FY+2"]["ebitda"]


# ---------------------------------------------------------------------------
# Live population: raw multi-period financials + a flat collateral list.
# ---------------------------------------------------------------------------

def test_export_to_xlsx_populates_raw_financial_cells(tmp_path):
    out_path = tmp_path / "populated.xlsx"
    financial_data = {"FY-Current": SAMPLE_PERIOD}

    export_to_xlsx("Test Co", str(out_path), financial_data=financial_data)
    wb = openpyxl.load_workbook(out_path)
    ws = wb["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    # FY-Current is column D.
    assert ws.cell(row=label_to_row["Revenue"], column=4).value == 1000
    assert ws.cell(row=label_to_row["Interest Paid"], column=4).value == 30
    assert ws.cell(row=label_to_row["Scheduled Principal Repayment"], column=4).value == 70

    # DSCR and Gross Leverage are still live Excel formulas, not baked numbers.
    dscr_cell = ws.cell(row=label_to_row["DSCR"], column=4).value
    gross_leverage_cell = ws.cell(row=label_to_row["Gross Leverage"], column=4).value
    assert isinstance(dscr_cell, str) and dscr_cell.startswith("=")
    assert isinstance(gross_leverage_cell, str) and gross_leverage_cell.startswith("=")


def test_export_to_xlsx_leaves_unpopulated_periods_blank(tmp_path):
    out_path = tmp_path / "partial.xlsx"
    export_to_xlsx("Test Co", str(out_path), financial_data={"FY-Current": SAMPLE_PERIOD})
    wb = openpyxl.load_workbook(out_path)
    ws = wb["Financial Spreading"]
    label_to_row = {ws.cell(row=r, column=1).value: r for r in range(1, ws.max_row + 1)}

    assert ws.cell(row=label_to_row["Revenue"], column=2).value is None  # FY-2
    assert ws.cell(row=label_to_row["Revenue"], column=3).value is None  # FY-1


def test_export_to_xlsx_writes_perfection_status_column(tmp_path):
    out_path = tmp_path / "collateral.xlsx"
    collateral_data = [
        {"asset_class": "HGV", "exposure": 100, "collateral_value": 80,
         "perfection_status": "Registered"},
    ]
    export_to_xlsx("Test Co", str(out_path), collateral_data=collateral_data)
    wb = openpyxl.load_workbook(out_path)
    ws = wb["Collateral & Exposure"]

    assert ws.cell(row=2, column=1).value == "HGV"
    assert ws.cell(row=2, column=9).value == "Registered"  # Perfection Status column


def test_export_to_xlsx_scales_total_row_for_multiple_collateral_assets(tmp_path):
    out_path = tmp_path / "multi_collateral.xlsx"
    collateral_data = [
        {"asset_class": "HGV", "exposure": 100, "collateral_value": 80, "perfection_status": "Registered"},
        {"asset_class": "Trailer", "exposure": 50, "collateral_value": 40, "perfection_status": "Registered"},
        {"asset_class": "Forklift", "exposure": 20, "collateral_value": 15, "perfection_status": "Pending"},
    ]
    export_to_xlsx("Test Co", str(out_path), collateral_data=collateral_data)
    wb = openpyxl.load_workbook(out_path)
    ws = wb["Collateral & Exposure"]

    # 3 assets -> rows 2-4, total on row 5.
    assert ws.cell(row=5, column=1).value == "Total"
    assert ws.cell(row=5, column=2).value == "=SUM(B2:B4)"
    assert ws.cell(row=5, column=7).value == "=SUM(G2:G4)"
    assert ws.cell(row=5, column=8).value == "=IFERROR(G5/B5,0)"

    memo = {}
    total_exposure = _evaluate(ws, "B", 5, memo)
    total_collateral_value = _evaluate(ws, "G", 5, memo)
    cv_pct = _evaluate(ws, "H", 5, memo)
    assert total_exposure == 170
    assert total_collateral_value == 135
    assert cv_pct == pytest.approx(135 / 170)
