import os
import glob
import argparse
from anthropic import Anthropic
from pypdf import PdfReader
from template_resolver import local_cam_template_path

client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

STYLE_PROMPT = (
    "Analyze these sample CAMs and extract writing style, tone, and standard "
    "risk phrasing:\n{text}"
)

TEMPLATE_PROMPT = (
    "Analyze the structure of these sample CAMs -- the section headings, the "
    "table columns, and the order information is presented in -- and produce "
    "a generic Markdown CAM template that mirrors that structure exactly.\n\n"
    "Critical: this template will be committed to a shared codebase, so it "
    "must contain ZERO real data from the samples. No real company names, "
    "people's names, dates, or figures. Replace every one of those with a "
    "bracketed [placeholder] describing what belongs there (e.g. "
    "[Borrower Legal Name], [Amount], [PD Grade]). Output only the Markdown "
    "template itself, nothing else.\n\nSample CAMs:\n{text}"
)

MOCK_STYLE_GUIDE = (
    "# Calibrated Style Guide (MOCK)\n\n"
    "This file was generated by `calibrate.py --mock` -- no Anthropic API call was made, "
    "so no real style or tone was actually extracted from your samples. Run without "
    "`--mock` (with `ANTHROPIC_API_KEY` set) to produce a real style guide.\n"
)

MOCK_TEMPLATE = (
    "# Credit Assessment Memorandum (MOCK)\n\n"
    "This file was generated by `calibrate.py --mock` -- no Anthropic API call was made, "
    "so this is a placeholder, not a template actually derived from your samples' "
    "structure. Run without `--mock` (with `ANTHROPIC_API_KEY` set) to derive a real one.\n\n"
    "**Borrower Name:** [Company Name]\n\n"
    "## Summary\n"
    "- **Verdict:** [Approve / Decline]\n"
)


def _read_sample_text():
    text_content = ""
    for path in glob.glob("inputs/calibration_samples/*.pdf"):
        reader = PdfReader(path)
        for page in reader.pages:
            text_content += page.extract_text() + "\n"
    return text_content


def run_calibration(deal_type, mock=False):
    if not mock and not os.environ.get("ANTHROPIC_API_KEY"):
        print("[INFO] ANTHROPIC_API_KEY not found. Running calibrate.py in --mock mode.")
        mock = True

    text_content = _read_sample_text()
    if not text_content:
        print("No sample PDFs found in inputs/calibration_samples/")
        return

    template_path = local_cam_template_path(deal_type)
    os.makedirs(os.path.dirname(template_path), exist_ok=True)

    if mock:
        # Deterministic, canned output -- no Anthropic client call of any kind.
        # This only exercises the PDF-reading and file-writing plumbing so the
        # pipeline can be smoke-tested without an API key or network access;
        # it does not, and should not, attempt to derive a real style guide or
        # template, since that's the one thing this script actually does.
        print(f"[MOCK] Read {len(text_content)} characters from "
              f"{len(glob.glob('inputs/calibration_samples/*.pdf'))} sample PDF(s).")
        with open("config/style_guide.md", "w") as f:
            f.write(MOCK_STYLE_GUIDE)
        print("[MOCK] Wrote placeholder `config/style_guide.md`.")
        with open(template_path, "w", encoding="utf-8") as f:
            f.write(MOCK_TEMPLATE)
        print(f"[MOCK] Wrote placeholder template to {template_path}.")
        return

    print("[1/2] Extracting writing style and tone...")
    style_response = client.messages.create(
        model="claude-3-7-sonnet-20250219",
        max_tokens=3000,
        messages=[{"role": "user", "content": STYLE_PROMPT.format(text=text_content[:12000])}]
    )
    with open("config/style_guide.md", "w") as f:
        f.write("# Calibrated Style Guide\n\n" + style_response.content[0].text)
    print("Calibration complete. Created `config/style_guide.md`.")

    print(f"[2/2] Deriving a '{deal_type}' CAM template from your samples...")
    template_response = client.messages.create(
        model="claude-3-7-sonnet-20250219",
        max_tokens=3000,
        messages=[{"role": "user", "content": TEMPLATE_PROMPT.format(text=text_content[:12000])}]
    )
    with open(template_path, "w", encoding="utf-8") as f:
        f.write(template_response.content[0].text)
    print(f"Derived template written to {template_path} -- this overrides the "
          f"shipped default for '{deal_type}' deals until you remove it.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--type", default="corporate_credit",
        help="Deal type these samples represent, e.g. corporate_credit, asset_finance "
             "(matches orchestrator.py's --type). Defaults to corporate_credit.",
    )
    parser.add_argument(
        "--mock", action="store_true",
        help="Skip all Anthropic API calls and write deterministic placeholder output "
             "instead -- for testing the PDF-reading/file-writing pipeline without an "
             "API key. Triggered automatically if ANTHROPIC_API_KEY isn't set.",
    )
    args = parser.parse_args()
    run_calibration(args.type, mock=args.mock)
